//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by JTools_ShellApp.rc
//
#define IDD_JTOOLS_SHELLAPP_DIALOG      102
#define IDR_MAINFRAME                   128
#define IDD_PREFERENCES                 129
#define IDD_COLOROREFS                  130
#define IDD_COLORPREFS                  130
#define IDC_STARTCORE                   1000
#define IDC_STOPCORE                    1001
#define IDC_CORESTATUS                  1002
#define IDC_SHOWMS                      1003
#define IDC_RESETLOGNX                  1004
#define IDC_SYSSTATUS                   1004
#define IDC_ACTIVITYWINDOW              1005
#define IDC_SYMBOL                      1005
#define IDC_SETTINGS                    1006
#define IDC_SYSTEMMODE                  1007
#define IDC_CORETIME                    1008
#define IDC_LAST                        1008
#define IDC_ONSTOP2                     1009
#define IDC_SIZE                        1009
#define IDC_STEP                        1010
#define IDC_TIMEFULL                    1011
#define IDC_SYSTEMTIME                  1012
#define IDC_TIME                        1012
#define IDC_CHARTREFRESH                1012
#define IDC_TIMESIM                     1013
#define IDC_TIMESTEP                    1014
#define IDC_MSGSEC                      1015
#define IDC_NETCHG                      1015
#define IDC_CLEAR                       1016
#define IDC_INTSTATUS                   1016
#define IDC_MAJORLOG                    1017
#define IDC_NAME                        1017
#define IDC_MAJORLOGSHOW                1018
#define IDC_RTJUMP                      1018
#define IDC_MAJORLOGFILE                1019
#define IDC_GRAPH                       1019
#define IDC_COMPACT                     1020
#define IDC_VOLGRAPH                    1020
#define IDC_BLACKSCHEME                 1020
#define IDC_VIEWLOG                     1021
#define IDC_WHITESCHEME                 1021
#define IDC_LEGGRAPH                    1021
#define IDC_CLEARLOG                    1022
#define IDC_DEFAULT                     1022
#define IDC_WINSHOW5                    1023
#define IDC_GRIDS                       1024
#define IDC_LISTFONT                    1024
#define IDC_MAINCOLORPICK1              1025
#define IDC_CIRCUITSTYLE                1025
#define IDC_CHARTPAUSE                  1026
#define IDC_MAINCOLORPICK2              1026
#define IDC_MAINCOLORPICK3              1027
#define IDC_SOLIDPFILL                  1027
#define IDC_MAINCOLORPICK4              1028
#define IDC_USEBBOBAND                  1028
#define IDC_MAINFGCOLORPICK1            1029
#define IDC_ROUNDLOTADJ                 1029
#define IDC_MAINFGCOLORPICK2            1030
#define IDC_AUTOTRADE                   1030
#define IDC_MAINFGCOLORPICK3            1031
#define IDC_STARTTIME                   1031
#define IDC_MAINFGCOLORPICK4            1032
#define IDC_STOPTIME                    1032
#define IDC_MAINCOLORPICK5              1033
#define IDC_EXCLUDETRADES               1033
#define IDC_MAINCOLORPICK6              1034
#define IDC_MAINCOLORPICK7              1035
#define IDC_MAINCOLORPICK8              1036
#define IDC_MAINCOLORPICK9              1037
#define IDC_MAINCOLORPICK10             1038
#define IDC_MAINCOLORPICK11             1039
#define IDC_MAINCOLORPICK12             1040
#define IDC_VOLUMEON                    1042
#define IDC_PRICEON                     1043
#define IDC_VOLUMEON2                   1044
#define IDC_LEGENDON                    1044
#define IDC_VOLUMEON3                   1045
#define IDC_SPLITSIZECHART              1045
#define IDC_REVTIME                     1047
#define IDC_SHOWISO                     1048
#define IDC_HOLLOWCANDLE                1050
#define IDC_BARS                        1052
#define IDC_CANDLESTICK                 1053
#define IDC_BARSPACING                  1054
#define IDC_BARSPACINGSPIN              1055
#define IDC_COMPWIDTH                   1056
#define IDC_COMPWIDTHSPIN               1057
#define IDC_QUARTERON                   1058
#define IDC_OTHERWIDTH                  1058
#define IDC_OTHERWIDTHSPIN              1059
#define IDC_DATAPOINTSPINNER            1060
#define IDC_STARTPOINTSPINNER           1061
#define IDC_TAPENAME                    1100
#define IDC_DLLNAME                     1101
#define IDC_HOUR                        1102
#define IDC_MINUTE                      1103
#define IDC_SECOND                      1104
#define IDC_CLOCKNONE                   1105
#define IDC_CHOOSEFILE                  1106
#define IDC_CHOOSEDLL                   1107
#define IDC_REALTIME                    1108
#define IDC_HISTORICAL                  1109
#define IDC_DELAYED                     1110
#define IDC_DELAYMINUTES                1111
#define IDC_DELAYRESOLUTION             1112
#define IDC_SAVESCREEN                  1113
#define IDC_EXCLUDEQUOTES               1114
#define IDC_EXCLUDEL2                   1115
#define IDC_EXCLUDEOPRA                 1116
#define IDC_RTSIM                       1117
#define IDC_ONSTART                     1118
#define IDC_ONSTOP                      1119
#define IDC_RESET                       1120
#define IDC_WINFG1                      1121
#define IDC_WINBG1                      1122
#define IDC_WINSHOW1                    1123
#define IDC_WINFG2                      1124
#define IDC_WINBG2                      1125
#define IDC_WINSHOW2                    1126
#define IDC_WINFG3                      1127
#define IDC_WINBG3                      1128
#define IDC_WINSHOW3                    1129
#define IDC_WINFG4                      1130
#define IDC_WINBG4                      1131
#define IDC_WINSHOW4                    1132
#define IDC_MAINCOLORCONTROL1           1133
#define IDC_MAINCOLORCONTROL2           1134
#define IDC_MAINCOLORCONTROL3           1135
#define IDC_MAINCOLORCONTROL4           1136
#define IDC_MAINCOLORCONTROL5           1137
#define IDC_MAINCOLORCONTROL6           1138
#define IDC_MAINCOLORCONTROL7           1139
#define IDC_MAINCOLORCONTROL8           1140
#define IDC_MAINCOLORCONTROL9           1141
#define IDC_MAINCOLORCONTROL10          1142
#define IDC_MAINCOLORCONTROL11          1143
#define IDC_MAINCOLORCONTROL12          1144
#define IDC_ACTIVITYLIMIT               1200
#define IDC_EXCLUDECRC                  1201
#define IDC_EDIT1                       1202
#define IDC_NXADDRESS                   1202
#define IDC_HARDMAX                     1202
#define IDC_MAXBARS                     1202
#define IDC_HARDMIN                     1203
#define IDC_HARDSCALE                   1204
#define IDC_VOLHARDMAX                  1205
#define IDC_VOLHARDSCALE                1206
#define IDC_BANDPERCENT                 1207
#define IDC_EXCHANGELIST                1227
#define IDC_SCALETOPRICE                1228
#define IDC_SCALETONBBO                 1229
#define IDC_SCALETOALL                  1230
#define IDC_SCALETOHARD                 1231
#define IDC_HARDLABEL1                  1232
#define IDC_HARDLABEL2                  1233
#define IDC_HARDLABEL3                  1234
#define IDC_SCALEVOLAUTO                1235
#define IDC_HARDLABEL4                  1236
#define IDC_HARDLABEL5                  1237
#define IDC_SCALEVOLHARD                1238
#define IDC_BANDINGLABEL                1239
#define IDC_TRADELAST                   1240
#define IDC_TRADEHIGH                   1241
#define IDC_NUMDATAPOINTS               1241
#define IDC_TRADELOW                    1242
#define IDC_STARTPOINT                  1242
#define IDC_BIDLAST                     1243
#define IDC_REXCHANGEFILTER             1243
#define IDC_BIDHIGH                     1244
#define IDC_RTLABEL1                    1244
#define IDC_BIDLOW                      1245
#define IDC_RTLABEL2                    1245
#define IDC_ASKLAST                     1246
#define IDC_RTLABEL3                    1246
#define IDC_ASKHIGH                     1247
#define IDC_RTLABEL4                    1247
#define IDC_ASKLOW                      1248
#define IDC_VOLCHART0                   1249
#define IDC_VOLCHART1                   1250
#define IDC_VOLCHART2                   1251
#define IDC_VOLCHART5                   1252
#define IDC_VOLCHART3                   1253
#define IDC_VOLCHART4                   1254

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        131
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         1248
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
